// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjiiuskshgkxeixxqxok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqaWl1c2tzaGdreGVpeHhxeG9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNjU2MzYsImV4cCI6MjA2NDk0MTYzNn0.mPg03s9BwG20nwBMGwTKLEGJvDjYlNEpdIhjEHrxADM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);